### ISSUE TITLE
ollama healthcheck

### ISSUE THREAD

**Issue by Marcelas751** [CatchTheTornado/pdf-extract-api#13]
Ollama image with latest tag don't have /health path for healthcheck. For this - use root path that returns "Ollama is running"

**Comment by Marcelas751** [comment]
But my opinion using "latest" tag is badly because you don't know about latest changes in your dependences

**Comment by pkarw** [comment]
Thanks! PR fixing it will be more than welcome to:)

**Comment by pkarw** [comment]
Fixed with https://github.com/CatchTheTornado/pdf-extract-api/pull/17
