### ISSUE TITLE
Use Local Ollama Instance Instead of Docker-Compose Instance

### ISSUE THREAD

**Issue by madhankumar2211** [CatchTheTornado/pdf-extract-api#23]
Hi,

I have already hosted Ollama on my local machine and would like to use that instance instead of the one created through the Docker Compose setup.

Could you please guide me on how I can configure the system to point to my local Ollama instance rather than using the Docker Compose-created instance?

Details:
I have Ollama running locally and accessible via [localhost:11434].
Currently, Docker Compose creates a separate instance, and I would prefer to use my local instance for efficiency.

What I've tried so far:
I have checked the Docker Compose configuration, but I'm unsure where to modify the settings to switch to my local instance.

Any guidance would be much appreciated!

Thanks in advance!

**Comment by pkarw** [comment]
Hey! Thanks for this issue, it might be really usefull - especially on Apple hardware which is not 100% supported by Docker! This is my first approach to this: https://github.com/CatchTheTornado/pdf-extract-api/pull/25/ check if it works for you, for me - I've got locally some problem with unexpectedly exiting celery worker which requires me still to debug why it happens before merging this to main

**Comment by pkarw** [comment]
Done with #25 - merged into master, please try it and let me know if works for you

**Comment by madhankumar2211** [comment]
Hey @pkarw,

Thanks so much for your quick response and for addressing the issue with the potential Docker Compose workaround!

I’ve gone ahead and tested the changes you merged in #25 , and I wanted to confirm that they’re actually doing what I needed.

Thanks again for your help - I really appreciate it!

**Comment by pkarw** [comment]
That's great to hear! Thanks!
