### ISSUE TITLE
OCR task failed.

### ISSUE THREAD

**Issue by PoleGeogry** [CatchTheTornado/pdf-extract-api#28]
hello, I used an Apple device to reproduce locally, but encountered the following situation:

{'state': 'FAILURE', 'status': 'Server disconnected without sending a response.'}
OCR task failed.

I use :  python client/cli.py ocr --file examples/example-mri.pdf --ocr_cache --prompt_file=examples/example-mri-remove-pii.txt
how to solve this problem?

**Comment by PoleGeogry** [comment]
turn off VPN

**Comment by pkarw** [comment]
Thanks @PoleGeogry! It might be usefull for other users as well, the problem with VPN was with OCR trying to get weights from internet or by accessing local server ports?
